### ISSUE TITLE
대시보드 추가 - 워드클라우드

### ISSUE THREAD

**Issue by qkr1839** [data-engineering-team4/kpop_dashboard#20]
### Issue 타입 ('x' 로 표기)
- [x] 기능 추가
- [ ] 기능 변경
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 문서 작성 및 수정

### 상세 내용
대시보드 추가 - 워드클라우드

### 예상 소요 시간
- 1일(금)

**Comment by 2hongbi** [comment]
1. snowflake Analytics schema에 REDDIT_POSTS_SUMMARY, REDDIT_COMMENTS_SUMMARY 테이블을 생성했습니다.

- REDDIT_POSTS_SUMMARY 빈도수 높은 단어 상위 10개
<img width="234" alt="스크린샷 2023-07-05 오후 4 19 20" src="https://github.com/data-engineering-team4/kpop_dashboard/assets/79040336/b61de246-fd70-4583-9833-2d6a0bff34fd">

- REDDIT_COMMENTS_SUMMARY 빈도수 높은 단어 상위 10개
<img width="238" alt="스크린샷 2023-07-05 오후 4 20 09" src="https://github.com/data-engineering-team4/kpop_dashboard/assets/79040336/40a3008f-b4f9-4fd9-9920-a62389d96b14">


2. https://prod-apnortheast-a.online.tableau.com/#/site/httpswwwgreppco/views/Wordcloud/RedditkpopWordCloud?:iid=2 
에 Wordcloud 생성한 작업물 업로드 해놓았습니다.



- Reddit Kpop 관련 게시물로 만든 WordCloud
![posts_wordcloud](https://github.com/data-engineering-team4/kpop_dashboard/assets/79040336/171b3714-3d94-448a-b9df-e3154d3fc337)
<img width="1378" alt="스크린샷 2023-07-05 오후 4 17 09" src="https://github.com/data-engineering-team4/kpop_dashboard/assets/79040336/5473e629-866a-4e27-a244-5a2e071a89a2">




- Reddit Kpop 관련 게시물들의 댓글로 만든 WordCloud
![comments](https://github.com/data-engineering-team4/kpop_dashboard/assets/79040336/3b70166c-9bd2-4f6c-96ca-604902e430c7)
<img width="1375" alt="스크린샷 2023-07-05 오후 4 17 33" src="https://github.com/data-engineering-team4/kpop_dashboard/assets/79040336/cba50619-3d02-4f30-8883-4e375eb7f9ae">

**Comment by 2hongbi** [comment]
불용어 더 추가해서 업데이트 했습니다.

- 게시물 워드클라우드
![posts_wordcloud](https://github.com/data-engineering-team4/kpop_dashboard/assets/79040336/5966c192-a47d-437e-a2ad-fefb66d970a3)

- 댓글 워드클라우드
![comments_wordcloud](https://github.com/data-engineering-team4/kpop_dashboard/assets/79040336/52714c70-f3ce-4460-8635-0f3039c8da1b)
