### ISSUE TITLE
장고 앱에 임베드

### ISSUE THREAD

**Issue by qkr1839** [data-engineering-team4/kpop_dashboard#21]
### Issue 타입 ('x' 로 표기)
- [x] 기능 추가
- [ ] 기능 변경
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 문서 작성 및 수정

### 상세 내용
장고 앱에 임베드

### 예상 소요 시간
- 주말

**Comment by sejeong-park** [comment]
작업에서 제외하기로 함
