### ISSUE TITLE
AWS EC2 배포 및 GitAction으로 CI/CD 적용

### ISSUE THREAD

**Issue by ujeongoh** [data-engineering-team4/kpop_dashboard#4]
### Issue 타입 ('x' 로 표기)
- [x] 기능 추가
- [ ] 기능 변경
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 문서 작성 및 수정

### 상세 내용
* AWS EC2 인스턴스 생성
* airflow 설치
* docker 설치
* AWS 배포
*

### 예상 소요 시간
- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5h`
- [x] `3h`

**Comment by sejeong-park** [comment]
GitAction에 CI/CD 적용 완료 후 close 하겠습니다 :)
